channels:
- conda-forge
dependencies:
- python
- numpy
- msmpi
- cloudpickle =3.0.0
- mpi4py =4.0.0
- pyzmq =26.2.0
- h5py =3.11.0
- matplotlib =3.9.2
- networkx =3.4
- pygraphviz =1.14
- ipython =8.27.0
