channels:
- conda-forge
dependencies:
- python
- numpy
- msmpi
- cloudpickle =3.0.0
- mpi4py =3.1.6
- tqdm =4.66.4
- pyzmq =26.0.3
- h5py =3.11.0
- h5io =0.2.3
- matplotlib =3.8.4
- networkx =3.3
- python-graphviz =0.20.3
- ipython =8.25.0