channels:
- conda-forge
dependencies:
- python
- numpy
- openmpi
- cloudpickle =3.0.0
- conda_subprocess =0.0.4
- mpi4py =3.1.6
- pyzmq =26.0.3
- h5py =3.11.0
- h5io =0.2.3
- matplotlib =3.9.1
- networkx =3.3
- pygraphviz =1.13
- ipython =8.26.0
