channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- numpy
- openmpi
- cloudpickle =3.0.0
- mpi4py =4.0.0
- pyzmq =26.1.1
- flux-core
- jupyter-book =1.0.0
- h5py =3.11.0
- h5io =0.2.4