channels:
- conda-forge
dependencies:
- python
- numpy
- openmpi
- cloudpickle =3.0.0
- mpi4py =3.1.6
- tqdm =4.66.2
- pyzmq =26.0.0
- flux-core =0.59.0
- flux-pmix =0.5.0
- versioneer =0.28
- h5py =3.11.0
- h5io =0.2.2