# This workflow is used to run the unittest of pyiron

name: Unittests-flux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: ubuntu-latest
          python-version: '3.12'
          label: linux-64-py-3-12-openmpi
          prefix: /Users/runner/miniconda3/envs/my-env
          environment-file: .ci_support/environment-openmpi.yml

        - operating-system: ubuntu-latest
          python-version: '3.12'
          label: linux-64-py-3-12-mpich
          prefix: /usr/share/miniconda3/envs/my-env
          environment-file: .ci_support/environment-mpich.yml

    steps:
    - uses: actions/checkout@v2
    - name: Extend environment openmpi
      shell: bash -l {0}
      timeout-minutes: 5
      if:  matrix.label == 'linux-64-py-3-12-openmpi'
      run: |
        printf '- coverage\n- flux-core =0.59.0\n- flux-pmix=0.5.0' >> ${{ matrix.environment-file }}
        cat ${{ matrix.environment-file }}
    - name: Extend environment mpich
      shell: bash -l {0}
      timeout-minutes: 5
      if:  matrix.label == 'linux-64-py-3-12-mpich'
      run: |
        printf '- coverage\n- flux-core =0.59.0' >> ${{ matrix.environment-file }}
        cat ${{ matrix.environment-file }}
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        miniforge-variant: Mambaforge
        channel-priority: strict
        auto-update-conda: true
        environment-file: ${{ matrix.environment-file }}
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 5
      run: |
        pip install versioneer[toml]==0.29
        pip install . --no-deps --no-build-isolation
        coverage run -a --omit="pympipool/_version.py,tests/*" -m unittest discover tests
    - name: Test Flux
      shell: bash -l {0}
      timeout-minutes: 5
      run: >
        flux start
        coverage run -a --omit="pympipool/_version.py,tests/*" -m unittest tests/test_flux_executor.py tests/test_executor_backend_flux.py;
        coverage xml
    - name: Coveralls
      if:  matrix.label == 'linux-64-py-3-12-openmpi'
      uses: coverallsapp/github-action@v2
